package com.aniket.allinoneauthentication;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.view.View;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;

import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.android.gms.tasks.TaskExecutors;
import com.google.firebase.FirebaseException;
import com.google.firebase.auth.AuthResult;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.PhoneAuthCredential;
import com.google.firebase.auth.PhoneAuthProvider;

import java.util.concurrent.TimeUnit;

public class phonenum extends AppCompatActivity {
    ImageView enter;
    TextView phone,code;
    FirebaseAuth mAuth;
    TextView smsCodeVerification;
    String verificationId;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_phonenum);

        phone = findViewById(R.id.phone);
        smsCodeVerification = findViewById(R.id.sendverification);
        code = findViewById(R.id.code);
        enter = findViewById(R.id.enter);

        enter.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                String phonenum = phone.getText().toString();
                String countrycode = code.getText().toString();
                if(phonenum.isEmpty() || phonenum.length() < 10)
                {
                    phone.setError("Please enter valid number");
                    phone.requestFocus();
                    return;
                }
                final String phone = "+"+countrycode+phonenum;
                sendVerificationCode(phone);
            }
        });
    }

    void sendVerificationCode(String phone)
    {
        PhoneAuthProvider.getInstance().verifyPhoneNumber(
                phone,
                60,
                TimeUnit.SECONDS,
                TaskExecutors.MAIN_THREAD,
                mcallback
        );
    }

    private PhoneAuthProvider.OnVerificationStateChangedCallbacks mcallback = new PhoneAuthProvider.OnVerificationStateChangedCallbacks() {
        @Override
        public void onCodeSent(String s, PhoneAuthProvider.ForceResendingToken forceResendingToken) {
            super.onCodeSent(s, forceResendingToken);
            //for every verification id there is a unique code generated by app which is later user to get credentials
            //if verification id and code id not a pair credential will be null
            //else there will be some thing
            verificationId = s;
//            Toast.makeText(phonenum.this,verificationId,Toast.LENGTH_SHORT).show();
        }

        @Override
        public void onVerificationCompleted(PhoneAuthCredential phoneAuthCredential) {
            try{
                String code = phoneAuthCredential.getSmsCode();
                if(code!=null)
                {
                    smsCodeVerification.setText(code);
                    verifycode(code);
                }
            }catch (Exception e)
            {

            }
        }

        @Override
        public void onVerificationFailed(FirebaseException e) {
            Toast.makeText(phonenum.this,e.getMessage(),Toast.LENGTH_SHORT).show();
        }
    };

    void verifycode(String code)
    {
        PhoneAuthCredential credential = PhoneAuthProvider.getCredential(verificationId,code);
        signInWithCredential(credential);
    }

    private void signInWithCredential(PhoneAuthCredential credential)
    {
        mAuth.signInWithCredential(credential)
                .addOnCompleteListener(new OnCompleteListener<AuthResult>() {
                    @Override
                    public void onComplete(@NonNull Task<AuthResult> task) {
                        if(task.isSuccessful())
                        {

                        }
                        else
                        {
                            Toast.makeText(phonenum.this,task.getException().getMessage(),Toast.LENGTH_SHORT).show();
                        }
                    }
                });
    }
}
